/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Address extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "county_province" })
    countyProvince: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_1" })
    line1: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_2" })
    line2?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_3" })
    line3?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "postcode" })
    postcode: string;
}
