/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Contact extends SpeakeasyBase {
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "business_phone" })
    businessPhone?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "business_phone_ext" })
    businessPhoneExt?: string;

    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cell_phone" })
    cellPhone?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "cell_phone_ext" })
    cellPhoneExt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "fax" })
    fax?: string;

    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "home_phone" })
    homePhone?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "home_phone_ext" })
    homePhoneExt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "primary_email" })
    primaryEmail?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "secondary_email" })
    secondaryEmail?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tertiary_email" })
    tertiaryEmail?: string;
}
