/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EstimateStatusEnum } from "./estimatestatusenum";
import { Expose, Transform } from "class-transformer";

export class EstimateSerializerListOutput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "approval_requested" })
    approvalRequested?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "date_accepted" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    dateAccepted: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "days_to_complete" })
    daysToComplete?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "days_until_start" })
    daysUntilStart?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "deadline" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    deadline?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "estimate_meld" })
    estimateMeld: number;

    @SpeakeasyMetadata()
    @Expose({ name: "estimate_status" })
    estimateStatus?: EstimateStatusEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "get_vendor_email" })
    getVendorEmail: string;

    @SpeakeasyMetadata()
    @Expose({ name: "get_vendor_invite_email" })
    getVendorInviteEmail: string;

    @SpeakeasyMetadata()
    @Expose({ name: "get_vendor_name" })
    getVendorName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "line_items" })
    lineItems: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "notes" })
    notes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "original_meld" })
    originalMeld: number;

    @SpeakeasyMetadata()
    @Expose({ name: "pm_fee" })
    pmFee?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "servicer" })
    servicer?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "total" })
    total: string;

    @SpeakeasyMetadata()
    @Expose({ name: "vendor" })
    vendor: number;
}
