/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum HubAccessLevelEnum {
    DirectOnly = "DIRECT_ONLY",
    AllNotifications = "ALL_NOTIFICATIONS",
    InvitedToHub = "INVITED_TO_HUB",
    HubAccess = "HUB_ACCESS",
}
