/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class ManagementAgentSerializerList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agent_preferences" })
    agentPreferences: number;

    @SpeakeasyMetadata()
    @Expose({ name: "contact" })
    contact?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "default_invoice_filter" })
    defaultInvoiceFilter?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "default_meld_filter" })
    defaultMeldFilter?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "is_active" })
    isActive?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management" })
    management: number;

    @SpeakeasyMetadata()
    @Expose({ name: "new_notification_settings" })
    newNotificationSettings?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "property_groups" })
    propertyGroups: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "role" })
    role: number;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title: string;

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;
}
