/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class MeldListViewProperty extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "county_province" })
    countyProvince?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "create_by" })
    createBy?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "is_active" })
    isActive?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "latitude" })
    latitude?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_1" })
    line1?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_2" })
    line2?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_3" })
    line3?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "longitude" })
    longitude?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "maintenance_notes" })
    maintenanceNotes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "other_address_details" })
    otherAddressDetails?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "postcode" })
    postcode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "property_name" })
    propertyName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "supplemental_data" })
    supplementalData?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "update_by" })
    updateBy?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;
}
