/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeldInvoiceListProperty } from "./meldinvoicelistproperty";
import { MeldInvoiceListViewUnit } from "./meldinvoicelistviewunit";
import { Expose, Transform, Type } from "class-transformer";

export class MeldInvoiceListMeld extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "brief_description" })
    briefDescription: string;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "prop" })
    @Type(() => MeldInvoiceListProperty)
    prop: MeldInvoiceListProperty;

    @SpeakeasyMetadata()
    @Expose({ name: "reference_id" })
    referenceId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    @Type(() => MeldInvoiceListViewUnit)
    unit: MeldInvoiceListViewUnit;
}
