/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class MeldInvoiceListDisplayAddress extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "county_province" })
    countyProvince?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "line_1" })
    line1?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "postcode" })
    postcode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "property_name" })
    propertyName?: string;
}
