/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeldExpendituresListProperty } from "./meldexpenditureslistproperty";
import { Expose, Transform, Type } from "class-transformer";

export class MeldExpendituresListUnitDisplayAddress extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "county_province" })
    countyProvince?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "create_by" })
    createBy?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "is_active" })
    isActive?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "line_1" })
    line1?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_2" })
    line2?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_3" })
    line3?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "postcode" })
    postcode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "property_name" })
    propertyName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "update_by" })
    updateBy?: Record<string, any>;

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;
}

export class MeldExpendituresListUnit extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "apartment" })
    apartment?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "approval_currency_limit" })
    approvalCurrencyLimit?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "building" })
    building?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    department?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "display_address" })
    @Type(() => MeldExpendituresListUnitDisplayAddress)
    displayAddress: MeldExpendituresListUnitDisplayAddress;

    @SpeakeasyMetadata()
    @Expose({ name: "floor" })
    floor?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "is_active" })
    isActive?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "maintenance_notes" })
    maintenanceNotes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "prop" })
    @Type(() => MeldExpendituresListProperty)
    prop: MeldExpendituresListProperty;

    @SpeakeasyMetadata()
    @Expose({ name: "room" })
    room?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "suite" })
    suite?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "unit_address" })
    unitAddress?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;
}
