/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeldExpendituresListProperty } from "./meldexpenditureslistproperty";
import { MeldExpendituresListUnit } from "./meldexpenditureslistunit";
import { PriorityEnum } from "./priorityenum";
import { Status5c6Enum } from "./status5c6enum";
import { WorkCategoryEnum } from "./workcategoryenum";
import { Expose, Transform, Type } from "class-transformer";

export class MeldExpendituresListMeld extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "assigned" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    assigned?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "assigner" })
    assigner: number;

    @SpeakeasyMetadata()
    @Expose({ name: "brief_description" })
    briefDescription: string;

    @SpeakeasyMetadata()
    @Expose({ name: "completion_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    completionDate?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "completion_notes" })
    completionNotes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "creator" })
    creator: number;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "due_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    dueDate?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "has_pets" })
    hasPets?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "has_registered_tenant" })
    hasRegisteredTenant?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "is_active" })
    isActive?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "maintenance_notes" })
    maintenanceNotes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management" })
    management: number;

    @SpeakeasyMetadata()
    @Expose({ name: "management_agent_closer" })
    managementAgentCloser?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "manager_cancellation_reason" })
    managerCancellationReason?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "manager_cancelled" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    managerCancelled?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "manager_canceller" })
    managerCanceller?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "marked_complete" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    markedComplete?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "meld_group" })
    meldGroup: number;

    @SpeakeasyMetadata()
    @Expose({ name: "notify_owner" })
    notifyOwner?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "parent" })
    parent?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "pets" })
    pets?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: PriorityEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "project" })
    project?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "prop" })
    @Type(() => MeldExpendituresListProperty)
    prop: MeldExpendituresListProperty;

    @SpeakeasyMetadata()
    @Expose({ name: "reason_cannot_complete" })
    reasonCannotComplete?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "recurring_meld" })
    recurringMeld?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "reference_id" })
    referenceId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "reviewing_tenant" })
    reviewingTenant?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "started" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    started?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: Status5c6Enum;

    @SpeakeasyMetadata()
    @Expose({ name: "tags" })
    tags: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "tenant_canceller" })
    tenantCanceller?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "tenant_presence_required" })
    tenantPresenceRequired?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "tenant_rating" })
    tenantRating?: any;

    @SpeakeasyMetadata()
    @Expose({ name: "tenant_review" })
    tenantReview?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tenant_review_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    tenantReviewDate?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    @Type(() => MeldExpendituresListUnit)
    unit: MeldExpendituresListUnit;

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "vendor_closer" })
    vendorCloser?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "work_category" })
    workCategory: WorkCategoryEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "work_location" })
    workLocation: string;
}
