/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeldListViewManagementAgent } from "./meldlistviewmanagementagent";
import { Expose, Type } from "class-transformer";

export class MeldListViewInHouseMeldServicer extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "agent" })
    @Type(() => MeldListViewManagementAgent)
    agent: MeldListViewManagementAgent;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;
}
