/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BaseBuilding } from "./basebuilding";
import { BaseFloor } from "./basefloor";
import { MeldInvoiceListDisplayAddress } from "./meldinvoicelistdisplayaddress";
import { MeldInvoiceListProperty } from "./meldinvoicelistproperty";
import { Expose, Type } from "class-transformer";

export class MeldInvoiceListViewUnit extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "apartment" })
    apartment?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "building" })
    @Type(() => BaseBuilding)
    building: BaseBuilding;

    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    department?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "display_address" })
    @Type(() => MeldInvoiceListDisplayAddress)
    displayAddress: MeldInvoiceListDisplayAddress;

    @SpeakeasyMetadata()
    @Expose({ name: "floor" })
    @Type(() => BaseFloor)
    floor: BaseFloor;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "prop" })
    @Type(() => MeldInvoiceListProperty)
    prop: MeldInvoiceListProperty;

    @SpeakeasyMetadata()
    @Expose({ name: "room" })
    room?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "suite" })
    suite?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit?: string;
}
