/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeldExpendituresListLineItem } from "./meldexpenditureslistlineitem";
import { MeldExpendituresListMeld } from "./meldexpenditureslistmeld";
import { StatusD0bEnum } from "./statusd0benum";
import { Expose, Transform, Type } from "class-transformer";

export class MeldExpendituresListViewSerializerDetail extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount: string;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata({ elemType: MeldExpendituresListLineItem })
    @Expose({ name: "expenditures_line_items" })
    @Type(() => MeldExpendituresListLineItem)
    expendituresLineItems: MeldExpendituresListLineItem[];

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "meld" })
    @Type(() => MeldExpendituresListMeld)
    meld: MeldExpendituresListMeld;

    @SpeakeasyMetadata()
    @Expose({ name: "notes" })
    notes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: StatusD0bEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;
}
