/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { IncomingMeldFrequencyEnum } from "./incomingmeldfrequencyenum";
import { SuccessfulMeldFrequencyEnum } from "./successfulmeldfrequencyenum";
import { TimezoneEnum } from "./timezoneenum";
import { Expose } from "class-transformer";

export class NotificationSettingsInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "incoming_meld_frequency" })
    incomingMeldFrequency?: IncomingMeldFrequencyEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "sms_notifications" })
    smsNotifications?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "successful_meld_frequency" })
    successfulMeldFrequency?: SuccessfulMeldFrequencyEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "timezone" })
    timezone?: TimezoneEnum;
}

export class NotificationSettings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "incoming_meld_frequency" })
    incomingMeldFrequency?: IncomingMeldFrequencyEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "sms_notifications" })
    smsNotifications?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "successful_meld_frequency" })
    successfulMeldFrequency?: SuccessfulMeldFrequencyEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "timezone" })
    timezone?: TimezoneEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "timezone_has_been_set" })
    timezoneHasBeenSet: boolean;
}
