/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeldExpendituresListViewSerializerList } from "./meldexpenditureslistviewserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedMeldExpendituresListViewSerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: MeldExpendituresListViewSerializerList })
    @Expose({ name: "results" })
    @Type(() => MeldExpendituresListViewSerializerList)
    results?: MeldExpendituresListViewSerializerList[];
}
