/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WorkEntrySerializerList } from "./workentryserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedWorkEntrySerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: WorkEntrySerializerList })
    @Expose({ name: "results" })
    @Type(() => WorkEntrySerializerList)
    results?: WorkEntrySerializerList[];
}
