/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ManagementAgentSerializerList } from "./managementagentserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedManagementAgentSerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: ManagementAgentSerializerList })
    @Expose({ name: "results" })
    @Type(() => ManagementAgentSerializerList)
    results?: ManagementAgentSerializerList[];
}
