/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BuildingSerializerList } from "./buildingserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedBuildingSerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: BuildingSerializerList })
    @Expose({ name: "results" })
    @Type(() => BuildingSerializerList)
    results?: BuildingSerializerList[];
}
