/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { FloorSerializerList } from "./floorserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedFloorSerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: FloorSerializerList })
    @Expose({ name: "results" })
    @Type(() => FloorSerializerList)
    results?: FloorSerializerList[];
}
