/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeldSerializerListOutput } from "./meldserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedMeldSerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: MeldSerializerListOutput })
    @Expose({ name: "results" })
    @Type(() => MeldSerializerListOutput)
    results?: MeldSerializerListOutput[];
}
