/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { VendorMeldFile } from "./vendormeldfile";
import { Expose, Type } from "class-transformer";

export class PaginatedVendorMeldFileList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: VendorMeldFile })
    @Expose({ name: "results" })
    @Type(() => VendorMeldFile)
    results?: VendorMeldFile[];
}
