/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PMApiVendorMeldFile } from "./pmapivendormeldfile";
import { Expose, Type } from "class-transformer";

export class PaginatedPMApiVendorMeldFileList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: PMApiVendorMeldFile })
    @Expose({ name: "results" })
    @Type(() => PMApiVendorMeldFile)
    results?: PMApiVendorMeldFile[];
}
