/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { MeldInvoiceSerializerList } from "./meldinvoiceserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedMeldInvoiceSerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: MeldInvoiceSerializerList })
    @Expose({ name: "results" })
    @Type(() => MeldInvoiceSerializerList)
    results?: MeldInvoiceSerializerList[];
}
