/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EstimateSerializerListOutput } from "./estimateserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedEstimateSerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: EstimateSerializerListOutput })
    @Expose({ name: "results" })
    @Type(() => EstimateSerializerListOutput)
    results?: EstimateSerializerListOutput[];
}
