/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Owner } from "./owner";
import { Expose, Type } from "class-transformer";

export class PaginatedOwnerList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: Owner })
    @Expose({ name: "results" })
    @Type(() => Owner)
    results?: Owner[];
}
