/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PropertyGroupSerializerList } from "./propertygroupserializerlist";
import { Expose, Type } from "class-transformer";

export class PaginatedPropertyGroupSerializerListList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: PropertyGroupSerializerList })
    @Expose({ name: "results" })
    @Type(() => PropertyGroupSerializerList)
    results?: PropertyGroupSerializerList[];
}
