/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PmAPITenantMeld } from "./pmapitenantmeld";
import { Expose, Type } from "class-transformer";

export class PaginatedPmAPITenantMeldList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: PmAPITenantMeld })
    @Expose({ name: "results" })
    @Type(() => PmAPITenantMeld)
    results?: PmAPITenantMeld[];
}
