/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PMApiMeldfile } from "./pmapimeldfile";
import { Expose, Type } from "class-transformer";

export class PaginatedPMApiMeldfileList extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "next" })
    next?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "previous" })
    previous?: string;

    @SpeakeasyMetadata({ elemType: PMApiMeldfile })
    @Expose({ name: "results" })
    @Type(() => PMApiMeldfile)
    results?: PMApiMeldfile[];
}
