/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { Expose, Type } from "class-transformer";

export class PatchedUnitInput extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "form, name=approval_currency_limit, multipart_form, name=approval_currency_limit",
    })
    @Expose({ name: "approval_currency_limit" })
    approvalCurrencyLimit?: string;

    @SpeakeasyMetadata({
        data: "form, name=current_residents, multipart_form, name=current_residents",
    })
    @Expose({ name: "current_residents" })
    currentResidents?: number[];

    @SpeakeasyMetadata({
        data: "form, name=maintenance_notes, multipart_form, name=maintenance_notes",
    })
    @Expose({ name: "maintenance_notes" })
    maintenanceNotes?: string;

    @SpeakeasyMetadata({ data: "form, name=property_id, multipart_form, name=property_id" })
    @Expose({ name: "property_id" })
    propertyId?: number;

    /**
     * This field indicates the particular dwelling within a larger building or complex. For example, in the address 123 Main St, Unit 302, the unit is 302
     */
    @SpeakeasyMetadata({ data: "form, name=unit, multipart_form, name=unit" })
    @Expose({ name: "unit" })
    unit?: string;

    @SpeakeasyMetadata({
        data: "form, name=unit_address;json=true, multipart_form, name=unit_address;json=true",
    })
    @Expose({ name: "unit_address" })
    @Type(() => Address)
    unitAddress?: Address;
}
