/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ManagementAgent } from "./managementagent";
import { PmAPIUnit } from "./pmapiunit";
import { ProjectTypeEnum } from "./projecttypeenum";
import { Expose, Transform, Type } from "class-transformer";

export class PmAPIProjectDetail extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: ManagementAgent })
    @Expose({ name: "coordinators" })
    @Type(() => ManagementAgent)
    coordinators: ManagementAgent[];

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "due_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    dueDate: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "melds" })
    melds: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "project_type" })
    projectType?: ProjectTypeEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "start_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    startDate: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    @Type(() => PmAPIUnit)
    unit?: PmAPIUnit;

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;
}
