/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum ProjectTypeEnum {
    Other = "OTHER",
    Renovation = "RENOVATION",
    Turn = "TURN",
    Mitigation = "MITIGATION",
}
