/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Transform } from "class-transformer";

export class PropertyInput extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "form, name=city, multipart_form, name=city" })
    @Expose({ name: "city" })
    city: string;

    @SpeakeasyMetadata({ data: "form, name=country, multipart_form, name=country" })
    @Expose({ name: "country" })
    country?: string;

    @SpeakeasyMetadata({ data: "form, name=county_province, multipart_form, name=county_province" })
    @Expose({ name: "county_province" })
    countyProvince: string;

    @SpeakeasyMetadata({ data: "form, name=line_1, multipart_form, name=line_1" })
    @Expose({ name: "line_1" })
    line1: string;

    @SpeakeasyMetadata({ data: "form, name=line_2, multipart_form, name=line_2" })
    @Expose({ name: "line_2" })
    line2?: string;

    @SpeakeasyMetadata({ data: "form, name=line_3, multipart_form, name=line_3" })
    @Expose({ name: "line_3" })
    line3?: string;

    @SpeakeasyMetadata({
        data: "form, name=maintenance_notes, multipart_form, name=maintenance_notes",
    })
    @Expose({ name: "maintenance_notes" })
    maintenanceNotes?: string;

    @SpeakeasyMetadata({
        data: "form, name=other_address_details, multipart_form, name=other_address_details",
    })
    @Expose({ name: "other_address_details" })
    otherAddressDetails?: string;

    @SpeakeasyMetadata({ data: "form, name=owners, multipart_form, name=owners" })
    @Expose({ name: "owners" })
    owners?: number[];

    @SpeakeasyMetadata({ data: "form, name=postcode, multipart_form, name=postcode" })
    @Expose({ name: "postcode" })
    postcode: string;

    @SpeakeasyMetadata({ data: "form, name=property_groups, multipart_form, name=property_groups" })
    @Expose({ name: "property_groups" })
    propertyGroups?: number[];

    @SpeakeasyMetadata({ data: "form, name=property_name, multipart_form, name=property_name" })
    @Expose({ name: "property_name" })
    propertyName?: string;

    @SpeakeasyMetadata({ data: "form, name=units, multipart_form, name=units" })
    @Expose({ name: "units" })
    units?: number[];
}

export class Property extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "county_province" })
    countyProvince: string;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "is_active" })
    isActive: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "line_1" })
    line1: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_2" })
    line2?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_3" })
    line3?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "maintenance_notes" })
    maintenanceNotes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "other_address_details" })
    otherAddressDetails?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "owners" })
    owners?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "postcode" })
    postcode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "property_groups" })
    propertyGroups?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "property_name" })
    propertyName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;
}
