/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Contact } from "./contact";
import { NotificationSettings, NotificationSettingsInput } from "./notificationsettings";
import { Expose, Transform, Type } from "class-transformer";

export class ResidentInput1 extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "form, name=address;json=true, multipart_form, name=address;json=true",
    })
    address?: any;

    @SpeakeasyMetadata({
        data: "form, name=contact;json=true, multipart_form, name=contact;json=true",
    })
    contact?: Contact;

    @SpeakeasyMetadata({ data: "form, name=first_name, multipart_form, name=first_name" })
    firstName: string;

    /**
     * Send an invite to the resident to access PropertyMeld
     */
    @SpeakeasyMetadata({ data: "form, name=invite, multipart_form, name=invite" })
    invite?: boolean;

    @SpeakeasyMetadata({ data: "form, name=last_name, multipart_form, name=last_name" })
    lastName: string;

    @SpeakeasyMetadata({ data: "form, name=middle_name, multipart_form, name=middle_name" })
    middleName?: string;

    @SpeakeasyMetadata({ data: "form, name=notes, multipart_form, name=notes" })
    notes?: string;

    @SpeakeasyMetadata({
        data: "form, name=notification_settings;json=true, multipart_form, name=notification_settings;json=true",
    })
    notificationSettings?: NotificationSettingsInput;

    @SpeakeasyMetadata({ data: "form, name=units, multipart_form, name=units" })
    units?: number[];
}

export class ResidentAddress extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    @SpeakeasyMetadata()
    @Expose({ name: "country" })
    country?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "county_province" })
    countyProvince: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_1" })
    line1: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_2" })
    line2?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "line_3" })
    line3?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "postcode" })
    postcode: string;
}

export class Resident extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    @Type(() => ResidentAddress)
    address?: ResidentAddress;

    @SpeakeasyMetadata()
    @Expose({ name: "contact" })
    @Type(() => Contact)
    contact?: Contact;

    @SpeakeasyMetadata()
    @Expose({ name: "created" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    created: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    /**
     * Send an invite to the resident to access PropertyMeld
     */
    @SpeakeasyMetadata()
    @Expose({ name: "invite" })
    invite?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "is_active" })
    isActive: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "middle_name" })
    middleName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "notes" })
    notes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "notification_settings" })
    @Type(() => NotificationSettings)
    notificationSettings?: NotificationSettings;

    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units?: number[];

    @SpeakeasyMetadata()
    @Expose({ name: "updated" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    updated: Date;
}

export class ResidentInput extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    @Type(() => ResidentAddress)
    address?: ResidentAddress;

    @SpeakeasyMetadata()
    @Expose({ name: "contact" })
    @Type(() => Contact)
    contact?: Contact;

    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    /**
     * Send an invite to the resident to access PropertyMeld
     */
    @SpeakeasyMetadata()
    @Expose({ name: "invite" })
    invite?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "middle_name" })
    middleName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "notes" })
    notes?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "notification_settings" })
    @Type(() => NotificationSettingsInput)
    notificationSettings?: NotificationSettingsInput;

    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units?: number[];
}
