/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum Status09fEnum {
    Draft = "DRAFT",
    Submitted = "SUBMITTED",
    InReview = "IN_REVIEW",
    Hold = "HOLD",
    Declined = "DECLINED",
    Approved = "APPROVED",
    Paid = "PAID",
}
