/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum StatusD0bEnum {
    Draft = "DRAFT",
    InReview = "IN_REVIEW",
    Hold = "HOLD",
    Approved = "APPROVED",
    Billed = "BILLED",
}
