/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class VendorInvite extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "form, name=company_name, multipart_form, name=company_name" })
    @Expose({ name: "company_name" })
    companyName?: string;

    @SpeakeasyMetadata({ data: "form, name=company_phone, multipart_form, name=company_phone" })
    @Expose({ name: "company_phone" })
    companyPhone?: string;

    @SpeakeasyMetadata({ data: "form, name=email, multipart_form, name=email" })
    @Expose({ name: "email" })
    email: string;

    @SpeakeasyMetadata({ data: "form, name=first_name, multipart_form, name=first_name" })
    @Expose({ name: "first_name" })
    firstName?: string;

    @SpeakeasyMetadata({ data: "form, name=last_name, multipart_form, name=last_name" })
    @Expose({ name: "last_name" })
    lastName?: string;

    @SpeakeasyMetadata({ data: "form, name=line_1, multipart_form, name=line_1" })
    @Expose({ name: "line_1" })
    line1?: string;

    @SpeakeasyMetadata({ data: "form, name=postcode, multipart_form, name=postcode" })
    @Expose({ name: "postcode" })
    postcode?: string;
}
