/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class EstimatesListSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    pmoAuth2Authentication: string;
}

export enum EstimatesListEstimateStatus {
    EstimateApproved = "ESTIMATE_APPROVED",
    EstimateClosed = "ESTIMATE_CLOSED",
    EstimateInProgress = "ESTIMATE_IN_PROGRESS",
    EstimateOwnerRejected = "ESTIMATE_OWNER_REJECTED",
    EstimatePendingAcceptance = "ESTIMATE_PENDING_ACCEPTANCE",
    EstimatePendingApproval = "ESTIMATE_PENDING_APPROVAL",
    EstimateSubmitted = "ESTIMATE_SUBMITTED",
    EstimateVendorRejected = "ESTIMATE_VENDOR_REJECTED",
}

export class EstimatesListRequest extends SpeakeasyBase {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Pm-Org" })
    xPmOrg: number;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=estimate_status" })
    estimateStatus?: EstimatesListEstimateStatus[];

    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=limit" })
    limit?: number;

    /**
     * The initial index from which to return the results.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=offset" })
    offset?: number;

    /**
     * Which field to use when ordering the results.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ordering" })
    ordering?: string;
}

export class EstimatesListResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    paginatedEstimateSerializerListList?: shared.PaginatedEstimateSerializerListList;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
