/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class ExpenditureListSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    pmoAuth2Authentication: string;
}

export enum ExpenditureListStatus {
    Approved = "APPROVED",
    Billed = "BILLED",
    Draft = "DRAFT",
    Hold = "HOLD",
    InReview = "IN_REVIEW",
}

export class ExpenditureListRequest extends SpeakeasyBase {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Pm-Org" })
    xPmOrg: number;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__gte" })
    createdGte?: Date;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__interval" })
    createdInterval?: Date;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__lte" })
    createdLte?: Date;

    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=limit" })
    limit?: number;

    /**
     * The initial index from which to return the results.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=offset" })
    offset?: number;

    /**
     * Which field to use when ordering the results.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ordering" })
    ordering?: string;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=status" })
    status?: ExpenditureListStatus[];
}

export class ExpenditureListResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    paginatedMeldExpendituresListViewSerializerListList?: shared.PaginatedMeldExpendituresListViewSerializerListList;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
