/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class InvoiceListSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    pmoAuth2Authentication: string;
}

/**
 * declined
 */
export enum InvoiceListDeclined {
    True = "true",
    False = "false",
}

/**
 * paid
 */
export enum InvoiceListPaid {
    False = "false",
    True = "true",
}

/**
 * status
 */
export enum InvoiceListStatus {
    Draft = "DRAFT",
    Submitted = "SUBMITTED",
    InReview = "IN_REVIEW",
    Hold = "HOLD",
    Declined = "DECLINED",
    Approved = "APPROVED",
    Paid = "PAID",
}

export class InvoiceListRequest extends SpeakeasyBase {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Pm-Org" })
    xPmOrg: number;

    /**
     * created__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__gte" })
    createdGte?: string;

    /**
     * created__interval
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__interval" })
    createdInterval?: string;

    /**
     * created__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__lte" })
    createdLte?: string;

    /**
     * declined
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=declined" })
    declined?: InvoiceListDeclined;

    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=limit" })
    limit?: number;

    /**
     * The initial index from which to return the results.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=offset" })
    offset?: number;

    /**
     * Which field to use when ordering the results.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ordering" })
    ordering?: string;

    /**
     * paid
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=paid" })
    paid?: InvoiceListPaid;

    /**
     * payment_requested__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=payment_requested__gte" })
    paymentRequestedGte?: string;

    /**
     * payment_requested__interval
     */
    @SpeakeasyMetadata({
        data: "queryParam, style=form;explode=true;name=payment_requested__interval",
    })
    paymentRequestedInterval?: string;

    /**
     * payment_requested__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=payment_requested__lte" })
    paymentRequestedLte?: string;

    /**
     * status
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=status" })
    status?: InvoiceListStatus;

    /**
     * vendor
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=vendor" })
    vendor?: string;

    /**
     * vendors
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=vendors" })
    vendors?: string;
}

export class InvoiceListResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    paginatedMeldInvoiceSerializerListList?: shared.PaginatedMeldInvoiceSerializerListList;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
