/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class MeldListSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    pmoAuth2Authentication: string;
}

/**
 * ack_approval
 */
export enum MeldListAckApproval {
    True = "true",
    False = "false",
}

/**
 * categories
 */
export enum MeldListCategories {
    ForRentSign = "FOR_RENT_SIGN",
    Evaluation = "EVALUATION",
    Turnover = "TURNOVER",
    Appliances = "APPLIANCES",
    BlindsWindowTreatments = "BLINDS_WINDOW_TREATMENTS",
    CircuitBreaker = "CIRCUIT_BREAKER",
    Cleaning = "CLEANING",
    Doors = "DOORS",
    Driveway = "DRIVEWAY",
    Drywall = "DRYWALL",
    Electrical = "ELECTRICAL",
    Exterior = "EXTERIOR",
    Fireplace = "FIREPLACE",
    Flooring = "FLOORING",
    GarageDoor = "GARAGE_DOOR",
    GarbageDisposal = "GARBAGE_DISPOSAL",
    General = "GENERAL",
    Hardware = "HARDWARE",
    Hvac = "HVAC",
    Interior = "INTERIOR",
    Landscaping = "LANDSCAPING",
    Locks = "LOCKS",
    OtherWorkCategory = "OTHER_WORK_CATEGORY",
    Painting = "PAINTING",
    OutsideWaterSpigot = "OUTSIDE_WATER_SPIGOT",
    PestControl = "PEST_CONTROL",
    Plumbing = "PLUMBING",
    Carpentry = "CARPENTRY",
    Pool = "POOL",
    Roofing = "ROOFING",
    Sewer = "SEWER",
    Shower = "SHOWER",
    Siding = "SIDING",
    SmokeDetectorCoDetectors = "SMOKE_DETECTOR_CO_DETECTORS",
    SoffitFascia = "SOFFIT_FASCIA",
    Stairs = "STAIRS",
    Toilet = "TOILET",
    TowelBars = "TOWEL_BARS",
    Violations = "VIOLATIONS",
    WasherDryer = "WASHER_DRYER",
    WaterDamage = "WATER_DAMAGE",
    WaterHeater = "WATER_HEATER",
    WaterSoftener = "WATER_SOFTENER",
    Windows = "WINDOWS",
}

/**
 * due_date_choice
 */
export enum MeldListDueDateChoice {
    Overdue = "overdue",
    Today = "today",
    Tomorrow = "tomorrow",
    Week = "week",
}

/**
 * ever_been_assigned
 */
export enum MeldListEverBeenAssigned {
    True = "true",
    False = "false",
}

/**
 * exp
 */
export enum MeldListExp {
    True = "true",
    False = "false",
}

/**
 * has_estimates
 */
export enum MeldListHasEstimates {
    False = "false",
    True = "true",
}

/**
 * maint_type
 */
export enum MeldListMaintType {
    One = "1",
    Two = "2",
}

/**
 * meldinvoice
 */
export enum MeldListMeldinvoice {
    True = "true",
    False = "false",
}

/**
 * Ordering
 */
export enum MeldListOrderBy {
    OwnerApprovalRequestDate = "owner_approval_request_date",
    MinusOwnerApprovalRequestDate = "-owner_approval_request_date",
}

/**
 * owner_approval
 */
export enum MeldListOwnerApproval {
    OwnerApprovalNotRequested = "OWNER_APPROVAL_NOT_REQUESTED",
    OwnerApprovalRequested = "OWNER_APPROVAL_REQUESTED",
    OwnerApprovalApproved = "OWNER_APPROVAL_APPROVED",
    OwnerApprovalNotApproved = "OWNER_APPROVAL_NOT_APPROVED",
    OwnerApprovalRequestedEstimates = "OWNER_APPROVAL_REQUESTED_ESTIMATES",
}

/**
 * priority
 */
export enum MeldListPriority {
    Low = "LOW",
    Medium = "MEDIUM",
    High = "HIGH",
}

/**
 * project_assigned
 */
export enum MeldListProjectAssigned {
    True = "true",
    False = "false",
}

/**
 * rating
 */
export enum MeldListRating {
    One = "1",
    Two = "2",
    Three = "3",
    Four = "4",
    Five = "5",
}

/**
 * recurring
 */
export enum MeldListRecurring {
    True = "true",
    False = "false",
}

/**
 * reminder_choice
 */
export enum MeldListReminderChoice {
    Overdue = "overdue",
    Today = "today",
    Tomorrow = "tomorrow",
    Week = "week",
}

/**
 * status
 */
export enum MeldListStatus {
    Open = "OPEN",
    ManagerCanceled = "MANAGER_CANCELED",
    TenantCanceled = "TENANT_CANCELED",
    PendingEstimates = "PENDING_ESTIMATES",
    PendingTenantAvailability = "PENDING_TENANT_AVAILABILITY",
    PendingMoreVendorAvailability = "PENDING_MORE_VENDOR_AVAILABILITY",
    PendingMoreManagementAvailability = "PENDING_MORE_MANAGEMENT_AVAILABILITY",
    PendingCompletion = "PENDING_COMPLETION",
    Completed = "COMPLETED",
    VendorCouldNotComplete = "VENDOR_COULD_NOT_COMPLETE",
    MaintenanceCouldNotComplete = "MAINTENANCE_COULD_NOT_COMPLETE",
    PendingVendor = "PENDING_VENDOR",
    PendingAssignment = "PENDING_ASSIGNMENT",
}

/**
 * tpr
 */
export enum MeldListTpr {
    False = "false",
    True = "true",
}

export class MeldListRequest extends SpeakeasyBase {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Pm-Org" })
    xPmOrg: number;

    /**
     * ack_approval
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ack_approval" })
    ackApproval?: MeldListAckApproval;

    /**
     * assigned_to_me
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=assigned_to_me" })
    assignedToMe?: string;

    /**
     * categories
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=categories" })
    categories?: MeldListCategories;

    /**
     * comments_gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=comments_gte" })
    commentsGte?: string;

    /**
     * comments_lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=comments_lte" })
    commentsLte?: string;

    /**
     * completed__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=completed__gte" })
    completedGte?: string;

    /**
     * completed__interval
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=completed__interval" })
    completedInterval?: string;

    /**
     * completed__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=completed__lte" })
    completedLte?: string;

    /**
     * created__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__gte" })
    createdGte?: string;

    /**
     * created__interval
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__interval" })
    createdInterval?: string;

    /**
     * created__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__lte" })
    createdLte?: string;

    /**
     * created__offset_lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=created__offset_lte" })
    createdOffsetLte?: string;

    /**
     * due_date_choice
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=due_date_choice" })
    dueDateChoice?: MeldListDueDateChoice;

    /**
     * due_date_gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=due_date_gte" })
    dueDateGte?: string;

    /**
     * due_date_lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=due_date_lte" })
    dueDateLte?: string;

    /**
     * ever_been_assigned
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=ever_been_assigned" })
    everBeenAssigned?: MeldListEverBeenAssigned;

    /**
     * exp
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=exp" })
    exp?: MeldListExp;

    /**
     * exp_s
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=exp_s" })
    expS?: string;

    /**
     * files_gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=files_gte" })
    filesGte?: string;

    /**
     * files_lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=files_lte" })
    filesLte?: string;

    /**
     * has_estimates
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=has_estimates" })
    hasEstimates?: MeldListHasEstimates;

    /**
     * invoice_s
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=invoice_s" })
    invoiceS?: string;

    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=limit" })
    limit?: number;

    /**
     * maint
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=maint" })
    maint?: string;

    /**
     * maint_type
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=maint_type" })
    maintType?: MeldListMaintType;

    /**
     * marked_complete__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=marked_complete__gte" })
    markedCompleteGte?: string;

    /**
     * marked_complete__interval
     */
    @SpeakeasyMetadata({
        data: "queryParam, style=form;explode=true;name=marked_complete__interval",
    })
    markedCompleteInterval?: string;

    /**
     * marked_complete__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=marked_complete__lte" })
    markedCompleteLte?: string;

    /**
     * meldinvoice
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=meldinvoice" })
    meldinvoice?: MeldListMeldinvoice;

    /**
     * The initial index from which to return the results.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=offset" })
    offset?: number;

    /**
     * Ordering
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=order_by" })
    orderBy?: MeldListOrderBy;

    /**
     * owner_approval
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=owner_approval" })
    ownerApproval?: MeldListOwnerApproval;

    /**
     * pg
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=pg" })
    pg?: string;

    /**
     * priority
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=priority" })
    priority?: MeldListPriority;

    /**
     * project
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=project" })
    project?: string;

    /**
     * project_assigned
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=project_assigned" })
    projectAssigned?: MeldListProjectAssigned;

    /**
     * prop
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=prop" })
    prop?: string;

    /**
     * rating
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=rating" })
    rating?: MeldListRating;

    /**
     * recurring
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=recurring" })
    recurring?: MeldListRecurring;

    /**
     * recurring_meld
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=recurring_meld" })
    recurringMeld?: string;

    /**
     * remindees
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=remindees" })
    remindees?: string;

    /**
     * reminder_choice
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=reminder_choice" })
    reminderChoice?: MeldListReminderChoice;

    /**
     * reminder_gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=reminder_gte" })
    reminderGte?: string;

    /**
     * reminder_lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=reminder_lte" })
    reminderLte?: string;

    /**
     * scheduled__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=scheduled__gte" })
    scheduledGte?: string;

    /**
     * scheduled__interval
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=scheduled__interval" })
    scheduledInterval?: string;

    /**
     * scheduled__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=scheduled__lte" })
    scheduledLte?: string;

    /**
     * scheduling
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=scheduling" })
    scheduling?: string;

    /**
     * status
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=status" })
    status?: MeldListStatus;

    /**
     * tags
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=tags" })
    tags?: string;

    /**
     * tags_ex
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=tags_ex" })
    tagsEx?: string;

    /**
     * tpr
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=tpr" })
    tpr?: MeldListTpr;

    /**
     * unit
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=unit" })
    unit?: string;

    /**
     * updated__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=updated__gte" })
    updatedGte?: string;

    /**
     * updated__interval
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=updated__interval" })
    updatedInterval?: string;

    /**
     * updated__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=updated__lte" })
    updatedLte?: string;

    /**
     * updated__offset_lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=updated__offset_lte" })
    updatedOffsetLte?: string;

    /**
     * vendor_scheduled__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=vendor_scheduled__gte" })
    vendorScheduledGte?: string;

    /**
     * vendor_scheduled__interval
     */
    @SpeakeasyMetadata({
        data: "queryParam, style=form;explode=true;name=vendor_scheduled__interval",
    })
    vendorScheduledInterval?: string;

    /**
     * vendor_scheduled__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=vendor_scheduled__lte" })
    vendorScheduledLte?: string;

    /**
     * wl__gte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=wl__gte" })
    wlGte?: string;

    /**
     * wl__lte
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=wl__lte" })
    wlLte?: string;
}

export class MeldListResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    paginatedMeldSerializerListList?: shared.PaginatedMeldSerializerListList;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
