/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

export class SchemaRetrieveSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({
        data: "security, scheme=true;type=http;subtype=bearer;name=Authorization",
    })
    pmoAuth2Authentication?: string;
}

export enum SchemaRetrieveFormat {
    Json = "json",
    Yaml = "yaml",
}

export class SchemaRetrieveRequest extends SpeakeasyBase {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata({ data: "header, style=simple;explode=false;name=X-Pm-Org" })
    xPmOrg: number;

    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=format" })
    format?: SchemaRetrieveFormat;
}

export class SchemaRetrieveResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    schemaRetrieve200ApplicationJSONObject?: Record<string, any>;

    @SpeakeasyMetadata()
    schemaRetrieve200ApplicationVndOaiOpenapiPlusJsonObject?: Record<string, any>;
}
